/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: empty.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "empty.grpc-c.h"
void   google__protobuf__empty__init
                     (Google__Protobuf__Empty         *message)
{
  static const Google__Protobuf__Empty init_value = GOOGLE__PROTOBUF__EMPTY__INIT;
  *message = init_value;
}
size_t google__protobuf__empty__get_packed_size
                     (const Google__Protobuf__Empty *message)
{
  assert(message->base.descriptor == &google__protobuf__empty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t google__protobuf__empty__pack
                     (const Google__Protobuf__Empty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &google__protobuf__empty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t google__protobuf__empty__pack_to_buffer
                     (const Google__Protobuf__Empty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &google__protobuf__empty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Google__Protobuf__Empty *
       google__protobuf__empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Google__Protobuf__Empty *)
     protobuf_c_message_unpack (&google__protobuf__empty__descriptor,
                                allocator, len, data);
}
void   google__protobuf__empty__free_unpacked
                     (Google__Protobuf__Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &google__protobuf__empty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define google__protobuf__empty__field_descriptors NULL
#define google__protobuf__empty__field_indices_by_name NULL
#define google__protobuf__empty__number_ranges NULL
const ProtobufCMessageDescriptor google__protobuf__empty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "google.protobuf.Empty",
  "Empty",
  "Google__Protobuf__Empty",
  "google.protobuf",
  sizeof(Google__Protobuf__Empty),
  0,
  google__protobuf__empty__field_descriptors,
  google__protobuf__empty__field_indices_by_name,
  0,  google__protobuf__empty__number_ranges,
  (ProtobufCMessageInit) google__protobuf__empty__init,
  NULL,NULL,NULL    /* reserved[123] */
};

size_t
google__protobuf__empty_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = google__protobuf__empty__get_packed_size((Google__Protobuf__Empty *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = google__protobuf__empty__pack((Google__Protobuf__Empty *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
google__protobuf__empty_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Google__Protobuf__Empty *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = google__protobuf__empty__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void google__protobuf__empty_free (Google__Protobuf__Empty * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    google__protobuf__empty__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}
