/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foo.grpc-c.h"
void   foo__sigle_stream_req__init
                     (Foo__SigleStreamReq         *message)
{
  static const Foo__SigleStreamReq init_value = FOO__SIGLE_STREAM_REQ__INIT;
  *message = init_value;
}
size_t foo__sigle_stream_req__get_packed_size
                     (const Foo__SigleStreamReq *message)
{
  assert(message->base.descriptor == &foo__sigle_stream_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__sigle_stream_req__pack
                     (const Foo__SigleStreamReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__sigle_stream_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__sigle_stream_req__pack_to_buffer
                     (const Foo__SigleStreamReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__sigle_stream_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__SigleStreamReq *
       foo__sigle_stream_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__SigleStreamReq *)
     protobuf_c_message_unpack (&foo__sigle_stream_req__descriptor,
                                allocator, len, data);
}
void   foo__sigle_stream_req__free_unpacked
                     (Foo__SigleStreamReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__sigle_stream_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__sigle_stream_rsp__init
                     (Foo__SigleStreamRsp         *message)
{
  static const Foo__SigleStreamRsp init_value = FOO__SIGLE_STREAM_RSP__INIT;
  *message = init_value;
}
size_t foo__sigle_stream_rsp__get_packed_size
                     (const Foo__SigleStreamRsp *message)
{
  assert(message->base.descriptor == &foo__sigle_stream_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__sigle_stream_rsp__pack
                     (const Foo__SigleStreamRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__sigle_stream_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__sigle_stream_rsp__pack_to_buffer
                     (const Foo__SigleStreamRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__sigle_stream_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__SigleStreamRsp *
       foo__sigle_stream_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__SigleStreamRsp *)
     protobuf_c_message_unpack (&foo__sigle_stream_rsp__descriptor,
                                allocator, len, data);
}
void   foo__sigle_stream_rsp__free_unpacked
                     (Foo__SigleStreamRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__sigle_stream_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__server_stream_req__init
                     (Foo__ServerStreamReq         *message)
{
  static const Foo__ServerStreamReq init_value = FOO__SERVER_STREAM_REQ__INIT;
  *message = init_value;
}
size_t foo__server_stream_req__get_packed_size
                     (const Foo__ServerStreamReq *message)
{
  assert(message->base.descriptor == &foo__server_stream_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__server_stream_req__pack
                     (const Foo__ServerStreamReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__server_stream_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__server_stream_req__pack_to_buffer
                     (const Foo__ServerStreamReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__server_stream_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__ServerStreamReq *
       foo__server_stream_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__ServerStreamReq *)
     protobuf_c_message_unpack (&foo__server_stream_req__descriptor,
                                allocator, len, data);
}
void   foo__server_stream_req__free_unpacked
                     (Foo__ServerStreamReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__server_stream_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__server_stream_rsp__init
                     (Foo__ServerStreamRsp         *message)
{
  static const Foo__ServerStreamRsp init_value = FOO__SERVER_STREAM_RSP__INIT;
  *message = init_value;
}
size_t foo__server_stream_rsp__get_packed_size
                     (const Foo__ServerStreamRsp *message)
{
  assert(message->base.descriptor == &foo__server_stream_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__server_stream_rsp__pack
                     (const Foo__ServerStreamRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__server_stream_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__server_stream_rsp__pack_to_buffer
                     (const Foo__ServerStreamRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__server_stream_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__ServerStreamRsp *
       foo__server_stream_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__ServerStreamRsp *)
     protobuf_c_message_unpack (&foo__server_stream_rsp__descriptor,
                                allocator, len, data);
}
void   foo__server_stream_rsp__free_unpacked
                     (Foo__ServerStreamRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__server_stream_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__client_stream_req__init
                     (Foo__ClientStreamReq         *message)
{
  static const Foo__ClientStreamReq init_value = FOO__CLIENT_STREAM_REQ__INIT;
  *message = init_value;
}
size_t foo__client_stream_req__get_packed_size
                     (const Foo__ClientStreamReq *message)
{
  assert(message->base.descriptor == &foo__client_stream_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__client_stream_req__pack
                     (const Foo__ClientStreamReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__client_stream_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__client_stream_req__pack_to_buffer
                     (const Foo__ClientStreamReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__client_stream_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__ClientStreamReq *
       foo__client_stream_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__ClientStreamReq *)
     protobuf_c_message_unpack (&foo__client_stream_req__descriptor,
                                allocator, len, data);
}
void   foo__client_stream_req__free_unpacked
                     (Foo__ClientStreamReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__client_stream_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__client_stream_rsp__init
                     (Foo__ClientStreamRsp         *message)
{
  static const Foo__ClientStreamRsp init_value = FOO__CLIENT_STREAM_RSP__INIT;
  *message = init_value;
}
size_t foo__client_stream_rsp__get_packed_size
                     (const Foo__ClientStreamRsp *message)
{
  assert(message->base.descriptor == &foo__client_stream_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__client_stream_rsp__pack
                     (const Foo__ClientStreamRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__client_stream_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__client_stream_rsp__pack_to_buffer
                     (const Foo__ClientStreamRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__client_stream_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__ClientStreamRsp *
       foo__client_stream_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__ClientStreamRsp *)
     protobuf_c_message_unpack (&foo__client_stream_rsp__descriptor,
                                allocator, len, data);
}
void   foo__client_stream_rsp__free_unpacked
                     (Foo__ClientStreamRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__client_stream_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__double_stream_req__init
                     (Foo__DoubleStreamReq         *message)
{
  static const Foo__DoubleStreamReq init_value = FOO__DOUBLE_STREAM_REQ__INIT;
  *message = init_value;
}
size_t foo__double_stream_req__get_packed_size
                     (const Foo__DoubleStreamReq *message)
{
  assert(message->base.descriptor == &foo__double_stream_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__double_stream_req__pack
                     (const Foo__DoubleStreamReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__double_stream_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__double_stream_req__pack_to_buffer
                     (const Foo__DoubleStreamReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__double_stream_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__DoubleStreamReq *
       foo__double_stream_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__DoubleStreamReq *)
     protobuf_c_message_unpack (&foo__double_stream_req__descriptor,
                                allocator, len, data);
}
void   foo__double_stream_req__free_unpacked
                     (Foo__DoubleStreamReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__double_stream_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__double_stream_rsp__init
                     (Foo__DoubleStreamRsp         *message)
{
  static const Foo__DoubleStreamRsp init_value = FOO__DOUBLE_STREAM_RSP__INIT;
  *message = init_value;
}
size_t foo__double_stream_rsp__get_packed_size
                     (const Foo__DoubleStreamRsp *message)
{
  assert(message->base.descriptor == &foo__double_stream_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__double_stream_rsp__pack
                     (const Foo__DoubleStreamRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__double_stream_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__double_stream_rsp__pack_to_buffer
                     (const Foo__DoubleStreamRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__double_stream_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__DoubleStreamRsp *
       foo__double_stream_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__DoubleStreamRsp *)
     protobuf_c_message_unpack (&foo__double_stream_rsp__descriptor,
                                allocator, len, data);
}
void   foo__double_stream_rsp__free_unpacked
                     (Foo__DoubleStreamRsp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__double_stream_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foo__sigle_stream_req__field_descriptors[2] =
{
  {
    "name1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__SigleStreamReq, name1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__SigleStreamReq, user_info),
    &info__req_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__sigle_stream_req__field_indices_by_name[] = {
  0,   /* field[0] = name1 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__sigle_stream_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__sigle_stream_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.sigle_stream_req",
  "SigleStreamReq",
  "Foo__SigleStreamReq",
  "foo",
  sizeof(Foo__SigleStreamReq),
  2,
  foo__sigle_stream_req__field_descriptors,
  foo__sigle_stream_req__field_indices_by_name,
  1,  foo__sigle_stream_req__number_ranges,
  (ProtobufCMessageInit) foo__sigle_stream_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__sigle_stream_rsp__field_descriptors[2] =
{
  {
    "message1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__SigleStreamRsp, message1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__SigleStreamRsp, user_info),
    &info__rsp_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__sigle_stream_rsp__field_indices_by_name[] = {
  0,   /* field[0] = message1 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__sigle_stream_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__sigle_stream_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.sigle_stream_rsp",
  "SigleStreamRsp",
  "Foo__SigleStreamRsp",
  "foo",
  sizeof(Foo__SigleStreamRsp),
  2,
  foo__sigle_stream_rsp__field_descriptors,
  foo__sigle_stream_rsp__field_indices_by_name,
  1,  foo__sigle_stream_rsp__number_ranges,
  (ProtobufCMessageInit) foo__sigle_stream_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__server_stream_req__field_descriptors[2] =
{
  {
    "name2",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__ServerStreamReq, name2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__ServerStreamReq, user_info),
    &info__req_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__server_stream_req__field_indices_by_name[] = {
  0,   /* field[0] = name2 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__server_stream_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__server_stream_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.server_stream_req",
  "ServerStreamReq",
  "Foo__ServerStreamReq",
  "foo",
  sizeof(Foo__ServerStreamReq),
  2,
  foo__server_stream_req__field_descriptors,
  foo__server_stream_req__field_indices_by_name,
  1,  foo__server_stream_req__number_ranges,
  (ProtobufCMessageInit) foo__server_stream_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__server_stream_rsp__field_descriptors[2] =
{
  {
    "message2",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__ServerStreamRsp, message2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__ServerStreamRsp, user_info),
    &info__rsp_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__server_stream_rsp__field_indices_by_name[] = {
  0,   /* field[0] = message2 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__server_stream_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__server_stream_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.server_stream_rsp",
  "ServerStreamRsp",
  "Foo__ServerStreamRsp",
  "foo",
  sizeof(Foo__ServerStreamRsp),
  2,
  foo__server_stream_rsp__field_descriptors,
  foo__server_stream_rsp__field_indices_by_name,
  1,  foo__server_stream_rsp__number_ranges,
  (ProtobufCMessageInit) foo__server_stream_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__client_stream_req__field_descriptors[2] =
{
  {
    "name3",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__ClientStreamReq, name3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__ClientStreamReq, user_info),
    &info__req_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__client_stream_req__field_indices_by_name[] = {
  0,   /* field[0] = name3 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__client_stream_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__client_stream_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.client_stream_req",
  "ClientStreamReq",
  "Foo__ClientStreamReq",
  "foo",
  sizeof(Foo__ClientStreamReq),
  2,
  foo__client_stream_req__field_descriptors,
  foo__client_stream_req__field_indices_by_name,
  1,  foo__client_stream_req__number_ranges,
  (ProtobufCMessageInit) foo__client_stream_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__client_stream_rsp__field_descriptors[2] =
{
  {
    "message3",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__ClientStreamRsp, message3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__ClientStreamRsp, user_info),
    &info__rsp_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__client_stream_rsp__field_indices_by_name[] = {
  0,   /* field[0] = message3 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__client_stream_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__client_stream_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.client_stream_rsp",
  "ClientStreamRsp",
  "Foo__ClientStreamRsp",
  "foo",
  sizeof(Foo__ClientStreamRsp),
  2,
  foo__client_stream_rsp__field_descriptors,
  foo__client_stream_rsp__field_indices_by_name,
  1,  foo__client_stream_rsp__number_ranges,
  (ProtobufCMessageInit) foo__client_stream_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__double_stream_req__field_descriptors[2] =
{
  {
    "name4",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__DoubleStreamReq, name4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__DoubleStreamReq, user_info),
    &info__req_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__double_stream_req__field_indices_by_name[] = {
  0,   /* field[0] = name4 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__double_stream_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__double_stream_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.double_stream_req",
  "DoubleStreamReq",
  "Foo__DoubleStreamReq",
  "foo",
  sizeof(Foo__DoubleStreamReq),
  2,
  foo__double_stream_req__field_descriptors,
  foo__double_stream_req__field_indices_by_name,
  1,  foo__double_stream_req__number_ranges,
  (ProtobufCMessageInit) foo__double_stream_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor foo__double_stream_rsp__field_descriptors[2] =
{
  {
    "message4",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__DoubleStreamRsp, message4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_info",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Foo__DoubleStreamRsp, user_info),
    &info__rsp_user_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__double_stream_rsp__field_indices_by_name[] = {
  0,   /* field[0] = message4 */
  1,   /* field[1] = user_info */
};
static const ProtobufCIntRange foo__double_stream_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__double_stream_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.double_stream_rsp",
  "DoubleStreamRsp",
  "Foo__DoubleStreamRsp",
  "foo",
  sizeof(Foo__DoubleStreamRsp),
  2,
  foo__double_stream_rsp__field_descriptors,
  foo__double_stream_rsp__field_indices_by_name,
  1,  foo__double_stream_rsp__number_ranges,
  (ProtobufCMessageInit) foo__double_stream_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};

size_t
foo__sigle_stream_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__sigle_stream_req__get_packed_size((Foo__SigleStreamReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__sigle_stream_req__pack((Foo__SigleStreamReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__sigle_stream_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__SigleStreamReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__sigle_stream_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__sigle_stream_req_free (Foo__SigleStreamReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__sigle_stream_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__sigle_stream_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__sigle_stream_rsp__get_packed_size((Foo__SigleStreamRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__sigle_stream_rsp__pack((Foo__SigleStreamRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__sigle_stream_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__SigleStreamRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__sigle_stream_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__sigle_stream_rsp_free (Foo__SigleStreamRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__sigle_stream_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__server_stream_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__server_stream_req__get_packed_size((Foo__ServerStreamReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__server_stream_req__pack((Foo__ServerStreamReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__server_stream_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__ServerStreamReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__server_stream_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__server_stream_req_free (Foo__ServerStreamReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__server_stream_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__server_stream_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__server_stream_rsp__get_packed_size((Foo__ServerStreamRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__server_stream_rsp__pack((Foo__ServerStreamRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__server_stream_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__ServerStreamRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__server_stream_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__server_stream_rsp_free (Foo__ServerStreamRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__server_stream_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__client_stream_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__client_stream_req__get_packed_size((Foo__ClientStreamReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__client_stream_req__pack((Foo__ClientStreamReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__client_stream_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__ClientStreamReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__client_stream_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__client_stream_req_free (Foo__ClientStreamReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__client_stream_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__client_stream_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__client_stream_rsp__get_packed_size((Foo__ClientStreamRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__client_stream_rsp__pack((Foo__ClientStreamRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__client_stream_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__ClientStreamRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__client_stream_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__client_stream_rsp_free (Foo__ClientStreamRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__client_stream_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__double_stream_req_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__double_stream_req__get_packed_size((Foo__DoubleStreamReq *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__double_stream_req__pack((Foo__DoubleStreamReq *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__double_stream_req_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__DoubleStreamReq *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__double_stream_req__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__double_stream_req_free (Foo__DoubleStreamReq * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__double_stream_req__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
foo__double_stream_rsp_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = foo__double_stream_rsp__get_packed_size((Foo__DoubleStreamRsp *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = foo__double_stream_rsp__pack((Foo__DoubleStreamRsp *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
foo__double_stream_rsp_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Foo__DoubleStreamRsp *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = foo__double_stream_rsp__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void foo__double_stream_rsp_free (Foo__DoubleStreamRsp * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    foo__double_stream_rsp__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

const char *foo__greeter__methods[] = {
    "/foo.Greeter/sigle_stream",
    "/foo.Greeter/sigle_stream2",
    "/foo.Greeter/server_stream",
    "/foo.Greeter/client_stream",
    "/foo.Greeter/double_stream",
};

grpc_c_method_funcs_t foo__greeter__methods__funcs[] = {
    {google__protobuf__empty_packer, google__protobuf__empty_unpacker, foo__sigle_stream_rsp_packer, foo__sigle_stream_rsp_unpacker },
    {foo__sigle_stream_req_packer, foo__sigle_stream_req_unpacker, google__protobuf__empty_packer, google__protobuf__empty_unpacker },
    {foo__server_stream_req_packer, foo__server_stream_req_unpacker, foo__server_stream_rsp_packer, foo__server_stream_rsp_unpacker },
    {foo__client_stream_req_packer, foo__client_stream_req_unpacker, foo__client_stream_rsp_packer, foo__client_stream_rsp_unpacker },
    {foo__double_stream_req_packer, foo__double_stream_req_unpacker, foo__double_stream_rsp_packer, foo__double_stream_rsp_unpacker },
};

int foo__greeter__sigle_stream__sync(grpc_c_client_t *client, 
                                       grpc_c_metadata_array_t *array, uint32_t flags, 
                                       Google__Protobuf__Empty *input, Foo__SigleStreamRsp **output, 
                                       grpc_c_status_t *status, long timeout)
{
    return grpc_c_client_request_sync(client, array, flags, foo__greeter__methods[0], 
                                      (void *)input, (void **)output, status, 
                                      &foo__greeter__methods__funcs[0], timeout);
}

int foo__greeter__sigle_stream__async(grpc_c_client_t *client, 
                                        grpc_c_metadata_array_t *array, uint32_t flags, 
                                        Google__Protobuf__Empty *input, 
                                        grpc_c_client_callback_t *cb, void *tag, long timeout)
{
    return grpc_c_client_request_async(client, array, flags, foo__greeter__methods[0], 
                                       input, cb, tag, &foo__greeter__methods__funcs[0], 
                                       timeout );
}

int foo__greeter__sigle_stream2__sync(grpc_c_client_t *client, 
                                        grpc_c_metadata_array_t *array, uint32_t flags, 
                                        Foo__SigleStreamReq *input, Google__Protobuf__Empty **output, 
                                        grpc_c_status_t *status, long timeout)
{
    return grpc_c_client_request_sync(client, array, flags, foo__greeter__methods[1], 
                                      (void *)input, (void **)output, status, 
                                      &foo__greeter__methods__funcs[1], timeout);
}

int foo__greeter__sigle_stream2__async(grpc_c_client_t *client, 
                                         grpc_c_metadata_array_t *array, uint32_t flags, 
                                         Foo__SigleStreamReq *input, 
                                         grpc_c_client_callback_t *cb, void *tag, long timeout)
{
    return grpc_c_client_request_async(client, array, flags, foo__greeter__methods[1], 
                                       input, cb, tag, &foo__greeter__methods__funcs[1], 
                                       timeout );
}

int foo__greeter__server_stream__stream(grpc_c_client_t *client, 
                                         grpc_c_metadata_array_t *array, uint32_t flags, 
                                         grpc_c_context_t **context, 
                                         long timeout)
{
    return grpc_c_client_request_stream(client, array, flags, foo__greeter__methods[2], 
                                        context, 0, 1, &foo__greeter__methods__funcs[2], 
                                        timeout );
}

int foo__greeter__client_stream__stream(grpc_c_client_t *client, 
                                         grpc_c_metadata_array_t *array, uint32_t flags, 
                                         grpc_c_context_t **context, 
                                         long timeout)
{
    return grpc_c_client_request_stream(client, array, flags, foo__greeter__methods[3], 
                                        context, 1, 0, &foo__greeter__methods__funcs[3], 
                                        timeout );
}

int foo__greeter__double_stream__stream(grpc_c_client_t *client, 
                                         grpc_c_metadata_array_t *array, uint32_t flags, 
                                         grpc_c_context_t **context, 
                                         long timeout)
{
    return grpc_c_client_request_stream(client, array, flags, foo__greeter__methods[4], 
                                        context, 1, 1, &foo__greeter__methods__funcs[4], 
                                        timeout );
}
