/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foo.grpc-c.h"

int
foo__greeter__service_init (grpc_c_server_t *server)
{
    int ret = 0;
    ret |=grpc_c_register_method(server, foo__greeter__methods[0], 
                          0, 0, foo__greeter__sigle_stream_cb,
                          &foo__greeter__methods__funcs[0]);

    ret |=grpc_c_register_method(server, foo__greeter__methods[1], 
                          0, 0, foo__greeter__sigle_stream2_cb,
                          &foo__greeter__methods__funcs[1]);

    ret |=grpc_c_register_method(server, foo__greeter__methods[2], 
                          0, 1, foo__greeter__server_stream_cb,
                          &foo__greeter__methods__funcs[2]);

    ret |=grpc_c_register_method(server, foo__greeter__methods[3], 
                          1, 0, foo__greeter__client_stream_cb,
                          &foo__greeter__methods__funcs[3]);

    ret |=grpc_c_register_method(server, foo__greeter__methods[4], 
                          1, 1, foo__greeter__double_stream_cb,
                          &foo__greeter__methods__funcs[4]);

    return ret;
}
