/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: info.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "info.grpc-c.h"
void   info__gpu_status__init
                     (Info__GpuStatus         *message)
{
  static const Info__GpuStatus init_value = INFO__GPU_STATUS__INIT;
  *message = init_value;
}
size_t info__gpu_status__get_packed_size
                     (const Info__GpuStatus *message)
{
  assert(message->base.descriptor == &info__gpu_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__gpu_status__pack
                     (const Info__GpuStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__gpu_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__gpu_status__pack_to_buffer
                     (const Info__GpuStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__gpu_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info__GpuStatus *
       info__gpu_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info__GpuStatus *)
     protobuf_c_message_unpack (&info__gpu_status__descriptor,
                                allocator, len, data);
}
void   info__gpu_status__free_unpacked
                     (Info__GpuStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &info__gpu_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   info__req_user_info__init
                     (Info__ReqUserInfo         *message)
{
  static const Info__ReqUserInfo init_value = INFO__REQ_USER_INFO__INIT;
  *message = init_value;
}
size_t info__req_user_info__get_packed_size
                     (const Info__ReqUserInfo *message)
{
  assert(message->base.descriptor == &info__req_user_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__req_user_info__pack
                     (const Info__ReqUserInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__req_user_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__req_user_info__pack_to_buffer
                     (const Info__ReqUserInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__req_user_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info__ReqUserInfo *
       info__req_user_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info__ReqUserInfo *)
     protobuf_c_message_unpack (&info__req_user_info__descriptor,
                                allocator, len, data);
}
void   info__req_user_info__free_unpacked
                     (Info__ReqUserInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &info__req_user_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   info__rsp_user_info__init
                     (Info__RspUserInfo         *message)
{
  static const Info__RspUserInfo init_value = INFO__RSP_USER_INFO__INIT;
  *message = init_value;
}
size_t info__rsp_user_info__get_packed_size
                     (const Info__RspUserInfo *message)
{
  assert(message->base.descriptor == &info__rsp_user_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__rsp_user_info__pack
                     (const Info__RspUserInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__rsp_user_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__rsp_user_info__pack_to_buffer
                     (const Info__RspUserInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__rsp_user_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info__RspUserInfo *
       info__rsp_user_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info__RspUserInfo *)
     protobuf_c_message_unpack (&info__rsp_user_info__descriptor,
                                allocator, len, data);
}
void   info__rsp_user_info__free_unpacked
                     (Info__RspUserInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &info__rsp_user_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor info__gpu_status__field_descriptors[3] =
{
  {
    "vendor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Info__GpuStatus, has_vendor),
    offsetof(Info__GpuStatus, vendor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usage",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Info__GpuStatus, has_usage),
    offsetof(Info__GpuStatus, usage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Info__GpuStatus, has_timestamp),
    offsetof(Info__GpuStatus, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__gpu_status__field_indices_by_name[] = {
  2,   /* field[2] = timestamp */
  1,   /* field[1] = usage */
  0,   /* field[0] = vendor */
};
static const ProtobufCIntRange info__gpu_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor info__gpu_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "info.GpuStatus",
  "GpuStatus",
  "Info__GpuStatus",
  "info",
  sizeof(Info__GpuStatus),
  3,
  info__gpu_status__field_descriptors,
  info__gpu_status__field_indices_by_name,
  1,  info__gpu_status__number_ranges,
  (ProtobufCMessageInit) info__gpu_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor info__req_user_info__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Info__ReqUserInfo, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Info__ReqUserInfo, has_score),
    offsetof(Info__ReqUserInfo, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Info__ReqUserInfo, has_timestamp),
    offsetof(Info__ReqUserInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__req_user_info__field_indices_by_name[] = {
  1,   /* field[1] = score */
  2,   /* field[2] = timestamp */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange info__req_user_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor info__req_user_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "info.reqUserInfo",
  "ReqUserInfo",
  "Info__ReqUserInfo",
  "info",
  sizeof(Info__ReqUserInfo),
  3,
  info__req_user_info__field_descriptors,
  info__req_user_info__field_indices_by_name,
  1,  info__req_user_info__number_ranges,
  (ProtobufCMessageInit) info__req_user_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor info__rsp_user_info__field_descriptors[3] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Info__RspUserInfo, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Info__RspUserInfo, has_score),
    offsetof(Info__RspUserInfo, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Info__RspUserInfo, has_timestamp),
    offsetof(Info__RspUserInfo, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__rsp_user_info__field_indices_by_name[] = {
  1,   /* field[1] = score */
  2,   /* field[2] = timestamp */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange info__rsp_user_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor info__rsp_user_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "info.rspUserInfo",
  "RspUserInfo",
  "Info__RspUserInfo",
  "info",
  sizeof(Info__RspUserInfo),
  3,
  info__rsp_user_info__field_descriptors,
  info__rsp_user_info__field_indices_by_name,
  1,  info__rsp_user_info__number_ranges,
  (ProtobufCMessageInit) info__rsp_user_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};

size_t
info__gpu_status_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = info__gpu_status__get_packed_size((Info__GpuStatus *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = info__gpu_status__pack((Info__GpuStatus *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
info__gpu_status_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Info__GpuStatus *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = info__gpu_status__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void info__gpu_status_free (Info__GpuStatus * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    info__gpu_status__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
info__req_user_info_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = info__req_user_info__get_packed_size((Info__ReqUserInfo *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = info__req_user_info__pack((Info__ReqUserInfo *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
info__req_user_info_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Info__ReqUserInfo *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = info__req_user_info__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void info__req_user_info_free (Info__ReqUserInfo * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    info__req_user_info__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}

size_t
info__rsp_user_info_packer (void *input, grpc_byte_buffer **buffer)
{
    uint8_t *out;
    size_t size = info__rsp_user_info__get_packed_size((Info__RspUserInfo *)input);
    out = gpr_malloc(sizeof(uint8_t) * size);
    size_t len = info__rsp_user_info__pack((Info__RspUserInfo *)input, out);
    grpc_slice slice = grpc_slice_new(out, len, gpr_free);
    *buffer = grpc_raw_byte_buffer_create(&slice, 1);
    grpc_slice_unref(slice);
    return len;
}

void *
info__rsp_user_info_unpacker (grpc_c_context_t *context, grpc_byte_buffer *buffer)
{
    Info__RspUserInfo *h = NULL;
    if (buffer != NULL) {
        struct ProtobufCAllocator allocator;
        grpc_byte_buffer_reader reader;
        grpc_byte_buffer_reader_init(&reader, buffer);
        grpc_slice slice;
        char *buf = NULL;

        slice = grpc_byte_buffer_reader_readall(&reader);
        buf = gpr_malloc(GRPC_SLICE_LENGTH(slice));
        memcpy(buf, GRPC_SLICE_START_PTR(slice), GRPC_SLICE_LENGTH(slice));

        h = info__rsp_user_info__unpack(grpc_c_get_protobuf_c_allocator(context, &allocator), GRPC_SLICE_LENGTH(slice), (void *)buf);
        gpr_free(buf);
        grpc_slice_unref(slice);
    }
    return h;
}

void info__rsp_user_info_free (Info__RspUserInfo * buf)
{
    struct ProtobufCAllocator allocator;
    if (buf == NULL) return;
    info__rsp_user_info__free_unpacked(buf, grpc_c_get_protobuf_c_allocator(NULL, &allocator));
}
